#!/bin/bash

checksum() {
	if which md5sum > /dev/null; then
		md5sum | awk '{print $1}'
	else
		md5
	fi
}

download-and-check() {
	while IFS=' ' read v t url expected; do
		echo "---> $v $t $url $expected"
		output="$(curl --fail -Ls $url | checksum)"
		if [[ "$expected" && "$output" != "$expected" ]]; then
			echo "!! checksum failed. got: $output"
			exit 2
		fi
	done
}

main() {
	set -eo pipefail; [[ "$TRACE" ]] && set -x
	for package in ./index/*; do
		if [[ "$(basename $package)" != "_version" ]]; then
			echo "===> $(basename $package)"
			cat "$package" \
				| grep -v '^\s*$' \
				| grep -v '^#' \
				| download-and-check
		fi
	done
}

main